1. Используя библиотеку numpy, решите систему линейных уравнений:

2x+y−z=8,

−3x−y+2z=−11,

−2x+y+2z=−3

In [5]:
import numpy as np

A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])
B = np.array([8, -11, -3])

solution = np.linalg.solve(A, B)
print("Решение системы уравнений:", solution)

Решение системы уравнений: [ 2.  3. -1.]


2. Решите квадратное уравнение(найдите его корни): $2x^2+4x−6=0$.
Используйте для этой задачи библиотеку math.

Для отработки материала, решение должно быть представлено через нахождение дискриминанта по формуле: $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}$$.

In [3]:
import math

# Коэффициенты квадратного уравнения
a = 2
b = 4
c = -6

# Вычисление дискриминанта
discriminant = b**2 - 4*a*c

# Вычисление корней уравнения
if discriminant >= 0:
    root1 = (-b + math.sqrt(discriminant)) / (2 * a)
    root2 = (-b - math.sqrt(discriminant)) / (2 * a)
    print("Корни уравнения:", root1, root2)
else:
    print("Корни не являются вещественными числами")

Корни уравнения: 1.0 -3.0


3. Вычислите синус угла $𝜋\over3$ с использованием первых четырех членов ряда Тейлора.
Серия Тейлора для синуса: $$x = x - {x^3\over3!} + {x^5\over5!} - {x^7\over7!} + ...$$
Использойте библиотеку math

In [15]:
import math

# Угол в радианах
x = math.pi / 3

# Вычисление синуса методом ряда Тейлора
sin_approximation = (x 
                     - (x**3) / math.factorial(3) 
                     + (x**5) / math.factorial(5) 
                     - (x**7) / math.factorial(7))

print("Приближенное значение синуса методом Тейлора:", round(sin_approximation, 2))

Приближенное значение синуса методом Тейлора: 0.87


4. Найдите площадь треугольника, если его стороны $a = 7, b = 8$, а угол между ними $С=45^o$
Подсказка: нужно найти площадь треугольника через синус угла по формуле:
$$A= {1\over2}absin(C)$$

In [24]:
import math

# Стороны треугольника и угол в градусах
a = 7
b = 8
angle_C_degrees = 45

# Конвертация угла в радианы
angle_C_radians = math.radians(angle_C_degrees)

# Вычисление площади треугольника
area = 0.5 * a * b * math.sin(angle_C_radians)
print("Площадь треугольника:", round(area,2))

Площадь треугольника: 19.8


5. В прямоугольном треугольнике угол между гипотенузой и прилежащим катетом равен 30 градусов. Найдите длину противолежащего катета, если длина прилежащего катета равна 10 единиц.

Используйите библиотеку math. Формула: $$tan(θ) = {a\over b},$$

где:
- $θ$ — угол между прилежащим катетом и гипотенузой,
- $a$ — противолежащий катет,
- $b$ — прилежащий катет.

In [29]:
import math

# Данные
angle_degrees = 30
b = 10

# Конвертация угла в радианы
angle_radians = math.radians(angle_degrees)

# Вычисление противолежащего катета
a = b * math.tan(angle_radians)
print("Длина противолежащего катета:", round(a,2))

Длина противолежащего катета: 5.77


6. Даны два вектора $A = [1, 2, 3]$ и $B = [4, 5, 6]$. Найдите их скалярное произведение.

In [34]:
import numpy as np

# Векторы A и B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Скалярное произведение
dot_product = np.dot(A, B)
print("Скалярное произведение A и B:", dot_product)

Скалярное произведение A и B: 32


7. Создайте случайную матрицу размером 5x5 и вычислите ее обратную матрицу и определитель с использованием библиотеки numpy.

In [10]:
import numpy as np

np.random.seed(0)
A = np.random.rand(5, 5)

determinant = np.linalg.det(A)
inverse = np.linalg.inv(A)

print(f"Определитель матрицы: {determinant}")
print("Обратная матрица:")
print(inverse)

Определитель матрицы: 0.009658225505885114
Обратная матрица:
[[-5.07364434  5.03275718 -8.39255671 -0.06015003  7.34064967]
 [ 4.65427318 -3.95688435  5.25001178 -0.37851197 -4.21225087]
 [-0.075115    5.9476881  -3.76550878 -2.19002299 -0.64201725]
 [ 1.81479262 -5.61065339  7.77189115  1.46191522 -3.73247774]
 [-1.15135146 -1.08584011 -2.62918337  1.95256026  3.31557249]]


8. Даны две матрицы: 
$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$ и $B = \begin{bmatrix} 9 & 8 & 7 \\ 6 & 5 & 4 \\ 3 & 2 & 1 \end{bmatrix}$

Найдите их сумму.
му. сумму.

In [42]:
import numpy as np

# Матрицы A и B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Сложение матриц
C = A + B
print("Сумма матриц A и B:\n", C)

Сумма матриц A и B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


9. Найдите ранг матрицы $B = \begin{bmatrix} 3 & 5 & 7 \\ 2 & 4 & 6 \\ 1 & 2 & 3 \end{bmatrix}$

In [44]:
import numpy as np

# Матрица B
B = np.array([[3, 5, 7], [2, 4, 6], [1, 2, 3]])

# Вычисление ранга матрицы
rank_B = np.linalg.matrix_rank(B)
print("Ранг матрицы B:", rank_B)

Ранг матрицы B: 2


10. Даны два вектора  $A=[1,2,3]$  и  $B=[4,5,6]$. Найдите угол между ними в градусах.

In [50]:
import numpy as np

# Векторы A и B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Скалярное произведение
dot_product = np.dot(A, B)

# Длины векторов
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)

# Вычисление косинуса угла
cos_theta = dot_product / (norm_A * norm_B)

# Вычисление угла в радианах
theta_radians = np.arccos(cos_theta)

# Конвертация угла в градусы
theta_degrees = np.degrees(theta_radians)
print("Угол между векторами в градусах:", round(theta_degrees,2))

Угол между векторами в градусах: 12.93


11. Напишите программу, которая вычисляет собственные значения и собственные векторы случайной симметричной матрицы размером 1000x1000. Проверьте, что матрица действительно симметрична, и подтвердите, что все собственные значения являются действительными числами.

In [2]:
import numpy as np

# 1. Создаем случайную матрицу 1000x1000
n = 1000
A = np.random.rand(n, n)

# 2. Преобразуем её в симметричную матрицу
A_symm = (A + A.T) / 2

# 3. Проверяем, что матрица симметрична
is_symmetric = np.allclose(A_symm, A_symm.T)
print(f"Матрица симметрична: {is_symmetric}")

# 4. Вычисляем собственные значения и собственные векторы
eigenvalues, eigenvectors = np.linalg.eigh(A_symm)

# 5. Проверяем, что все собственные значения действительные
are_real = np.all(np.isreal(eigenvalues))
print(f"Все собственные значения действительные: {are_real}")

# Выводим результаты
print(f"Первое собственное значение: {eigenvalues[0]}")
print(f"Первый собственный вектор: {eigenvectors[:, 0]}")

Матрица симметрична: True
Все собственные значения действительные: True
Первое собственное значение: -12.837419494320725
Первый собственный вектор: [-4.14729917e-02 -1.47375016e-03  1.51047660e-02  4.00456367e-02
  3.49324583e-02 -2.34230925e-03  8.49234025e-03  4.85178609e-02
  9.57297528e-03  1.69126906e-02 -2.45483574e-03  7.97832345e-03
 -7.46605989e-03  2.44908852e-03 -6.89572352e-03 -5.34600421e-03
  2.92233653e-02 -4.14598401e-02 -2.25575019e-02 -1.93721961e-03
  4.95221238e-02 -6.44550882e-03 -4.00528031e-02  4.84961754e-02
  7.52973618e-02  7.51964039e-03 -1.42908801e-02  3.26641985e-02
  1.28437835e-02  6.29578032e-03 -2.24748975e-02 -3.67853818e-02
  4.26649409e-02  1.17207738e-02  1.60352367e-02  2.76451996e-02
 -2.31434599e-02  4.93829128e-04 -2.15447826e-03 -5.97176571e-02
 -3.87355670e-02  7.36148144e-02 -4.36397374e-02 -1.02940197e-02
 -3.22453812e-03  4.18955344e-02  1.47701702e-02 -5.29369802e-02
  1.15128380e-03 -3.34661491e-02 -3.72867983e-02 -1.38756314e-02
  7.944

12. Расчет расстояния между двумя точками на сфере (формула гаверсинуса) Задача: Напишите функцию, которая вычисляет расстояние между двумя точками на поверхности Земли, заданными их широтой и долготой, используя формулу гаверсинуса.

Радиус Земли примите за 6371 км

Используйте:

`math.radians(), math.sin(), math.cos(), math.sqrt(), math.atan2()`

Формула Гаверсинуса выглядит так: 
$$d = 2r \cdot \arcsin\left( \sqrt{ \sin^2\left( \dfrac{\Delta\phi}{2} \right) + \cos(\phi_1) \cdot \cos(\phi_2) \cdot \sin^2\left( \dfrac{\Delta\lambda}{2} \right) } \right)$$).рица.

In [37]:
import math

def haversine(lat1, lon1, lat2, lon2):
    R = 6371
    
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])

    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    distance = R * c
    
    return distance

# Координаты Москвы
lat1 = 55.7558
lon1 = 37.6173

# Координаты Нью-Йорка
lat2 = 40.7128
lon2 = -74.0060
print(haversine(lat1, lon1, lat2, lon2))  

7510.264607579636


13. Для матрицы 
$A = \begin{bmatrix} 6 & 2 \\ 2 & 3  \\  \end{bmatrix}$ найдите наибольшее собственное значение методом степенной итерации.

## Вспомогательный материал для решения задачи

### Метод степенной итерации

Метод степенной итерации используется для нахождения наибольшего по модулю собственного значения и соответствующего собственного вектора матрицы.

Основная идея метода заключается в том, что при многократном умножении случайного вектора на матрицу $ A $, доминирующее (наибольшее по модулю) собственное значение постепенно проявляется, так как собственные компоненты, соответствующие меньшим собственным значениям, затухают.

#### Формулировка метода степенной итерации:

1. Пусть $ A $ — квадратная матрица размера $ n \times n $.
2. Начните с произвольного ненулевого вектора $ b_0 $ (как правило, его компоненты можно задать случайно).
3. Повторяйте следующие шаги до достижения сходимости:

$$
b_{k+1} = \frac{A b_k}{||A b_k||}
$$

где:
- $ b_k $ — вектор на $ k $-ой итерации.
- $ ||A b_k|| $ — норма вектора, чаще всего используется евклидова норма.

4. После нескольких итераций вектор $ b_k $ будет приближаться к собственному вектору, соответствующему наибольшему по модулю собственному значению матрицы $ A $.

5. Найдите приближение к собственному значению с использованием вектора $ b_k $:

$$
\lambda_k = \frac{b_k^T A b_k}{b_k^T b_k}
$$

где:
- $ \lambda_k $ — приближение наибольшего собственного значения на $ k $-ой итерации.
- $ b_k^T $ — транспонированный вектор $ b_k $.

Этот метод работает хорошо для симметричных матриц и матриц с разными по величине собственными значениями.

In [83]:
import numpy as np

# Матрица A
A = np.array([[6, 2], [2, 3]])

# Начальное приближение вектора (с преобразованием в float)
b = np.array([1, 1], dtype=float)
tol = 1e-6
max_iter = 100

# Метод степенной итерации
for _ in range(max_iter):
    b_next = np.dot(A, b)
    b_next_norm = np.linalg.norm(b_next)
    b_next /= b_next_norm  
    
    if np.linalg.norm(b_next - b) < tol:
        break
    b = b_next

# Собственное значение
largest_eigenvalue = np.dot(b, np.dot(A, b))
print("Наибольшее собственное значение:", round(largest_eigenvalue,2))

Наибольшее собственное значение: 7.0


14. Найдите радиус описанной окружности треугольника с длинами сторон $a = 3$, $b = 4$, $c = 5$.

Радиус описанной окружности треугольника $R$ можно найти по формуле:
$R = \frac{abc}{4A}$
где $a$, $b$, $c$ — длины сторон треугольника, а $A$ — его площадь.

In [56]:
import math

# Длины сторон треугольника
a, b, c = 3, 4, 5

# Полупериметр
s = (a + b + c) / 2

# Площадь треугольника (формула Герона)
area = math.sqrt(s * (s - a) * (s - b) * (s - c))

# Вычисление радиуса описанной окружности
R = (a * b * c) / (4 * area)
print("Радиус описанной окружности:", R)

Радиус описанной окружности: 2.5


15. Найдите длину кривой $\mathbf{r}(t) = (t^2, t^3, t)$ на интервале $[0, 1]$.

Длина кривой $\mathbf{r}(t) = (x(t), y(t), z(t))$ вычисляется по формуле:
$$ L = \int_a^b \sqrt{\left(\frac{dx}{dt}\right)^2 + \left(\frac{dy}{dt}\right)^2 + \left(\frac{dz}{dt}\right)^2} dt $$

In [65]:
import numpy as np
import math

# Производные компонентов кривой
def dxdt(t):
    return 2*t

def dydt(t):
    return 3*t**2

def dzdt(t):
    return 1

# Метод численного интегрирования (метод прямоугольников)
a, b = 0, 1
n = 1000
dt = (b - a) / n
t = np.linspace(a, b, n)

# Вычисление длины кривой
ds = np.sqrt(dxdt(t)**2 + dydt(t)**2 + dzdt(t)**2)
length = np.sum(ds) * dt
print("Длина кривой:", round(length,2))

Длина кривой: 1.86


16. Найдите минимальное значение функции $f(x) = (x - 2)^2$ на отрезке $[0, 5]$ методом золотого сечения.

#### Формула метода золотого сечения:

Метод золотого сечения используется для минимизации унимодальной функции на заданном интервале. Этот метод позволяет последовательно сужать область поиска минимума до заданной точности.

Число золотого сечения $\varphi$ (phi) вычисляется по следующей формуле:
$\varphi = \frac{1 + \sqrt{5}}{2} \approx 1.618$

Процесс сужения интервала:
- Пусть начальный интервал поиска $[a, b]$.
- Определяются две новые точки внутри интервала: 
  - $c = b - \frac{b - a}{\varphi}$
  - $d = a + \frac{b - a}{\varphi}$

- Вычисляются значения функции $f(c)$ и $f(d)$. Далее возможны два варианта:
  1. Если $f(c) < f(d)$, то новый интервал поиска: $[a, d]$.
  2. Если $f(c) \geq f(d)$, то новый интервал поиска: $[c, b]$.

Процесс продолжается до тех пор, пока длина интервала не станет меньше заданной точности $\epsilon$.

#### Пояснение:
Метод золотого сечения эффективно находит минимум функции за меньшее количество шагов по сравнению с методом перебора или равномерного деления интервала, так как использует пропорциональные отношения, характерные для числа золотого сечения.

In [91]:
import math

# Функция для минимизации
def f(x):
    return (x - 2)**2

# Параметры метода золотого сечения
a, b = 0, 5
phi = (1 + math.sqrt(5)) / 2
tol = 1e-6

# Метод золотого сечения
while abs(b - a) > tol:
    c = b - (b - a) / phi
    d = a + (b - a) / phi
    if f(c) < f(d):
        b = d
    else:
        a = c

# Минимальное значение функции
min_x = (a + b) / 2
min_value = f(min_x)
print("Минимальное значение функции:", min_value, "при x =", min_x)

Минимальное значение функции: 1.5214922752069158e-14 при x = 2.000000123348785


17. Найдите угол между плоскостями $2x + 3y + 4z = 5$ и $x - 2y + z = 0$.

Угол между двумя векторами определяется по формуле:

$$
\cos(\theta) = \frac{\mathbf{n_1} \cdot \mathbf{n_2}}{|\mathbf{n_1}| |\mathbf{n_2}|},
$$

где:
- $\mathbf{n_1} \cdot \mathbf{n_2}$ — скалярное произведение нормальных векторов,
- $|\mathbf{n_1}|$ и $|\mathbf{n_2}|$ — длины нормальных векторов (их нормы).

In [100]:
import numpy as np
import math

# Коэффициенты нормальных векторов
n1 = np.array([2, 3, 4])
n2 = np.array([1, -2, 1])

# Скалярное произведение и длины векторов
dot_product = np.dot(n1, n2)
norm_n1 = np.linalg.norm(n1)
norm_n2 = np.linalg.norm(n2)

# Вычисление угла
cos_theta = dot_product / (norm_n1 * norm_n2)
theta = np.degrees(np.arccos(cos_theta))

print("Угол между плоскостями:", theta, "градусов")

Угол между плоскостями: 90.0 градусов


18. Найдите объем параллелепипеда, если его образуют векторы $\mathbf{a} = (11, 2, 3)$, $\mathbf{b} = (4, 5, 6)$ и $\mathbf{c} = (7, 8, 9)$.

Объем параллелепипеда, образованного тремя векторами $\mathbf{a}$, $\mathbf{b}$ и $\mathbf{c}$, вычисляется как абсолютное значение смешанного произведения: $$V=∣a⋅(b×c)∣$$

P.S. ошибки в векторах нет, в векторе а действительно стоит `11`, а не `1`

In [112]:
import numpy as np

# Векторы
a = np.array([11, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# Смешанное произведение
volume = abs(np.dot(a, np.cross(b, c)))
print("Объем параллелепипеда:", volume)

Объем параллелепипеда: 30


19. Найдите координаты центра описанной окружности треугольника с вершинами $A(1, 2)$, $B(3, 4)$, $C(5, 1)$.

#### Формула для вычисления центра описанной окружности:

Центр описанной окружности для треугольника с вершинами $A(x_1, y_1)$, $B(x_2, y_2)$ и $C(x_3, y_3)$ можно найти с использованием пересечения серединных перпендикуляров к сторонам треугольника.

Для вычисления координат центра окружности $(x_o, y_o)$ используются следующие уравнения:

$$
x_o = \frac{ (x_1^2 + y_1^2)(y_2 - y_3) + (x_2^2 + y_2^2)(y_3 - y_1) + (x_3^2 + y_3^2)(y_1 - y_2) }{ 2 \cdot \Delta }
$$
$$
y_o = \frac{ (x_1^2 + y_1^2)(x_3 - x_2) + (x_2^2 + y_2^2)(x_1 - x_3) + (x_3^2 + y_3^2)(x_2 - x_1) }{ 2 \cdot \Delta }
$$

где $\Delta$ — определитель, равный удвоенной площади треугольника, вычисляемый как:

$
\Delta = \left| x_1(y_2 - y_3) + x_2(y_3 - y_1) + x_3(y_1 - y_2) \right|
$

#### Пояснение:

Координаты центра окружности определяются через пересечение серединных перпендикуляров к сторонам треугольника. Формулы учитывают координаты вершин треугольника и позволяют найти центр окружности.

In [4]:
import numpy as np

# Координаты вершин треугольника
A = np.array([1, 2])
B = np.array([3, 4])
C = np.array([5, 1])

# Вычисление площади треугольника через определитель
def triangle_area(A, B, C):
    return abs(A[0] * (B[1] - C[1]) + B[0] * (C[1] - A[1]) + C[0] * (A[1] - B[1])) / 2

# Определитель площади треугольника
Delta = triangle_area(A, B, C)
# Перепишем с использованием новых функций
fi_1 = lambda x, y: x**2 + y**2
fi_2 = lambda x, y: x - y

# Используем fi_1 и fi_2 в формулах для координат центра описанной окружности
x_o = (fi_1(A[0], A[1]) * fi_2(B[1], C[1]) +
       fi_1(B[0], B[1]) * fi_2(C[1], A[1]) +
       fi_1(C[0], C[1]) * fi_2(A[1], B[1])) / (2 * Delta)

y_o = (fi_1(A[0], A[1]) * fi_2(C[0], B[0]) +
       fi_1(B[0], B[1]) * fi_2(A[0], C[0]) +
       fi_1(C[0], C[1]) * fi_2(B[0], A[0])) / (2 * Delta)

print("Координаты центра описанной окружности:", (x_o, y_o))

Координаты центра описанной окружности: (-6.2, -3.8)


20. Найдите площадь многоугольника с вершинами $P_1(1, 2)$, $P_2(4, 5)$, $P_3(7, 2)$, $P_4(4, 0)$.

Площадь многоугольника с вершинами $(x_1, y_1), (x_2, y_2), \dots, (x_n, y_n)$ вычисляется по формуле:

$$
A = \frac{1}{2} \left| \sum_{i=1}^{n-1} (x_i y_{i+1} - x_{i+1} y_i) + (x_n y_1 - x_1 y_n) \right|
$$

где $(x_1, y_1), (x_2, y_2), \dots, (x_n, y_n)$ — координаты вершин многоугольника, расположенных в порядке обхода.

In [122]:
import numpy as np

# Координаты вершин многоугольника
vertices = np.array([[1, 2], [4, 5], [7, 2], [4, 0]])

# Вычисление площади
n = len(vertices)
area = 0
for i in range(n):
    x1, y1 = vertices[i]
    x2, y2 = vertices[(i + 1) % n]
    area += x1 * y2 - x2 * y1

area = abs(area) / 2
print("Площадь многоугольника:", area)

Площадь многоугольника: 15.0
